# Generated by Django 5.1.3 on 2024-11-26 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a", models.CharField(max_length=100)),
                ("team_b", models.CharField(max_length=100)),
                ("game_date", models.DateField()),
                (
                    "score_team_a",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Final score for Team A.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "score_team_b",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Final score for Team B.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "winner",
                    models.CharField(
                        blank=True,
                        help_text="Winner of the game (i.e, Team A, Team B, or Draw).",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpreadLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spread_team_a",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Spread for Team A (e.g., -3.5).",
                        max_digits=4,
                    ),
                ),
                (
                    "odds_team_a",
                    models.IntegerField(
                        help_text="Odds for Team A spread (e.g., -110)."
                    ),
                ),
                (
                    "spread_team_b",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Spread for Team B (e.g., +3.5).",
                        max_digits=4,
                    ),
                ),
                (
                    "odds_team_b",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Odds for Team B spread (e.g., +110).",
                        max_digits=6,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spread_lines",
                        to="my_book.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TotalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_points",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total points line (e.g., 46.5).",
                        max_digits=5,
                    ),
                ),
                (
                    "odds_over",
                    models.IntegerField(help_text="Odds for Over (e.g., -110)."),
                ),
                (
                    "odds_under",
                    models.IntegerField(help_text="Odds for Under (e.g., +110)."),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total_lines",
                        to="my_book.game",
                    ),
                ),
            ],
        ),
    ]
