# Generated by Django 5.1.3 on 2024-11-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spreadline",
            name="odds_team_b",
            field=models.IntegerField(help_text="Odds for Team B spread (e.g., +110)."),
        ),
    ]
