# Generated by Django 5.1.3 on 2024-11-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_book", "0003_player_remove_totalline_game_remove_game_winner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="over_under_points",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0.0,
                help_text="Over/ Under points for both teams",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="score_team_a",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0.0,
                help_text="Final score for Team A.",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="score_team_b",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0.0,
                help_text="Final score for Team B.",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="total_points",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0.0,
                help_text="Total points for both teams",
                max_digits=5,
                null=True,
            ),
        ),
    ]
