# Generated by Django 5.1.3 on 2024-12-08 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_book", "0006_parlay2_parlay3_parlay4"),
    ]

    operations = [
        migrations.RenameField(
            model_name="straight", old_name="single_bet", new_name="single_bet1",
        ),
    ]
