# Generated by Django 5.1.3 on 2024-12-08 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_book", "0008_action_created_at_parlay2_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="straight",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
