# Generated by Django 5.1.3 on 2024-12-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_book", "0009_straight_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="over_under_points",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                help_text="Over/ Under points for both teams",
                max_digits=5,
            ),
        ),
    ]
