# Generated by Django 5.1.3 on 2024-12-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_book", "0011_alter_game_over_under_points"),
    ]

    operations = [
        migrations.DeleteModel(name="Parlay2",),
    ]
