# Generated by Django 5.1.4 on 2025-01-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_book", "0013_alter_singlebet_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="league",
            field=models.CharField(
                choices=[("NFL", "NFL"), ("NCAA", "NCAA")], default=1, max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="name",
            field=models.CharField(default="game_name", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="team_a_logo_url",
            field=models.URLField(
                blank=True,
                default="https://as2.ftcdn.net/v2/jpg/05/97/47/95/1000_F_597479556_7bbQ7t4Z8k3xbAloHFHVdZIizWK1PdOo.jpghttps://as2.ftcdn.net/v2/jpg/05/97/47/95/1000_F_597479556_7bbQ7t4Z8k3xbAloHFHVdZIizWK1PdOo.jpg",
                max_length=400,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="team_b_logo_url",
            field=models.URLField(
                blank=True,
                default="https://as2.ftcdn.net/v2/jpg/05/97/47/95/1000_F_597479556_7bbQ7t4Z8k3xbAloHFHVdZIizWK1PdOo.jpghttps://as2.ftcdn.net/v2/jpg/05/97/47/95/1000_F_597479556_7bbQ7t4Z8k3xbAloHFHVdZIizWK1PdOo.jpg",
                max_length=400,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="fav",
            field=models.CharField(
                help_text="Exact match of either Team A's name or Team B's name.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="over_under_points",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                help_text="Over/ Under points for both teams.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="total_points",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0.0,
                help_text="Total final points for both teams.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="game", unique_together={("game_date", "team_a", "team_b")},
        ),
    ]
