# Generated by Django 5.1.4 on 2025-01-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_book", "0014_game_league_game_name_game_team_a_logo_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_finished",
            field=models.BooleanField(
                default=False, help_text="Indicates if the game is finished."
            ),
        ),
    ]
